rec1Value Constrained-Octet-String ::= '000A01'H
rec2Value Constrained-Octet-String ::= '00A00'H
rec3Value Constrained-Octet-String ::= '0A'H
rec4Value Constrained-Octet-String ::= 'A0'H
rec5Value Constrained-Octet-String ::= 'AA'H
rec6Value Constrained-Octet-String ::= '000000'H
