rec1value PCCH-Message ::= 
{
  message c1 : paging : 
      {
        systemInfoModification true,
        nonCriticalExtension 
        {
        }
      }
}
rec2value PCCH-Message ::= 
{
  message c1 : paging : 
      {
      }
} 
