rec1Value My-Int-N ::= 0
rec2Value My-Int-N ::= -100
rec3Value My-Int-N ::= 112222200455
rec4Value My-Int-N ::= 99999999
rec5Value My-Int-N ::= 5445
rec6Value My-Int-N ::= -456678678
rec7Value My-Int-N ::= 1
rec8Value My-Int-N ::= -1
rec9Value My-Int-N ::= c
rec10Value My-Int-N ::= b
rec11Value My-Int-N ::= a
rec12Value My-Int-N ::= 1
